# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\Teacher: bcrypt
        AppBundle\Entity\Director: bcrypt
        AppBundle\Entity\Student: bcrypt

    role_hierarchy:
        ROLE_STUDENT: [ROLE_USER, ROLE_STUDENT]
        ROLE_TEACHER:  [ROLE_USER, ROLE_TEACHER]
        ROLE_DIRECTOR: [ROLE_USER, ROLE_DIRECTOR]
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

#    access_control:
#        - { path: ^/admin, roles: ROLE_DIRECTOR }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|bundles|uploads|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - AppBundle\Security\LoginFormAuthenticator
            logout: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
#            form_login: ~
#
