services:
    _defaults:
        autowire: true
        autoconfigure: true

        public: false
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    namer.user_images:
        public: true
        class: AppBundle\Namer\UserPhotoNamer
        tags:
          - { name: namer }
    AppBundle\DataFixtures\FakePhoneNumberProvider:
        public: true
        tags:
            -  { name: nelmio_alice.faker.provider }
    AppBundle\Form\UpdateForm:
        tags:
          - { name: form.type }